server:
    port: 8060

block:
    ##设定哈希值的计算难度
    ##difficulty: 4
    
    ##当前节点p2pserver端口号
    p2pport: 7000
    ##要连接的节点地址
    address: ws://10.21.204.97:7001
    ##要连接的节点地址_2
    address_2: ws://10.21.204.97:7002
    ##要连接的节点地址_3
    address_3: ws://10.21.204.97:7003