server:
    port: 8080

block:
    ##设定哈希值的计算难度
    difficulty: 4

    # ##当前节点p2pserver端口号------for node1
    # p2pport: 7001
    # ##要连接的节点地址
    # address: ws://10.21.204.97:7002
    # ##要连接的节点地址_2
    # address_2: ws://10.21.204.97:7003

    ##当前节点p2pserver端口号------for node2
    p2pport: 7002
    ##要连接的节点地址
    address: ws://10.21.204.97:7001
    ##要连接的节点地址_2
    address_2: ws://10.21.204.97:7003

    # ##当前节点p2pserver端口号-------for node3
    # p2pport: 7003
    # ##要连接的节点地址
    # address: ws://10.21.204.97:7001
    # ##要连接的节点地址_2
    # address_2: ws://10.21.204.97:7002
    
